version: "3"
services:
    ros:
      container_name: ros-compose
      image: joelimgu/geicar:dev
      environment:
        - ROS_DOMAIN_ID=1
      network_mode: host
      volumes:
        - ...:/root/ros_sw/
      devices:
        - USB ...

