version: "3"
services:
    ros:
      container_name: ros-compose
      image: joelimgu/geicar:dev
      environment:
        - ROS_DOMAIN_ID=1
      network_mode: host
      volumes:
        - ./ros2_ws:/root/ros_sw/
      devices:
        - /dev/ttyUSB0:/dev/ttyUSB0
        - /dev/video0:/dev/video0
      entrypoint: "sleep inf"

